# Generated by Django 5.0.2 on 2026-03-06 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (7–20 digits, spaces, +, -, (, ) allowed).",
                        regex="^\\+?[\\d\\s().\\-]{7,20}$",
                    )
                ],
            ),
        ),
    ]
